
server:
  port: 10000

spring:
  cloud:
    gateway:
      routes:
      
      - id: employeeModule
        uri: http://localhost:8081/
        predicates:
        - Path=/employee/**
        filters:
        - StripPrefix=1
        
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/consumer/**