server:
  port: 8020

spring:
  application:
    name:Spring_Swagger
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    # HikariCP \u9023\u7DDA\u6C60\u512A\u5316
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Swagger/OpenAPI \u914D\u7F6E
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true